language: python
sudo: false
env:
  matrix:
  - SPLIT="1/4" TEST_SYMPY="true"
  - SPLIT="2/4" TEST_SYMPY="true"
  - SPLIT="3/4" TEST_SYMPY="true"
  - SPLIT="4/4" TEST_SYMPY="true"
  global:
    - secure: "YIEZal9EBTL+fg2YmoZoS8Bvt3eAVUOZjb38CtqpzR2CCSXWoUk35KG23m2NknlY1iKfYJyt7XWBszT/VKOQEbWQq7PIakV4vIByrWacgBxy1x3WC+rZoW7TX+JJiL+y942qIYbMoNMMB8xFpE5RDLSjSecMpFhJJXoafVTvju8="
dist: trusty

python:
  - 3.6

matrix:
  include:
    - python: 3.6
      env:
        - TEST_ASCII="true"
        - TEST_OPT_DEPENDENCY="numpy scipy gmpy2 matplotlib theano llvmlite autowrap python-symengine=0.3.*"
      addons:
        apt:
          packages:
            # for theano
            - libatlas-dev
            - libatlas-base-dev
            - liblapack-dev
            - gfortran
            - python-scipy

    - python: 3.6
      env:
        - TEST_SLOW="true"
        - SPLIT="1/3"
    - python: 3.6
      env:
        - TEST_SLOW="true"
        - SPLIT="2/3"
    - python: 3.6
      env:
        - TEST_SLOW="true"
        - SPLIT="3/3"

    # Everything here and below is in the allow_failures. The need to be
    # duplicated here and in that section below.

    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="1/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="2/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="3/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="4/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy

  allow_failures:
    # PyPy randomly fails because of some PyPy bugs (Fatal RPython error: AssertionError)
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="1/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="2/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="3/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy
    - python: "pypy"
      env:
        - TEST_SYMPY="true"
        - SPLIT="4/4"
        - FASTCACHE="false"
      addons:
        apt:
          sources:
            - pypy
          packages:
            - pypy

before_install:
  - if [[ "${FASTCACHE}" != "false" ]]; then
      pip install fastcache;
    fi
  - |
    if [[ "${TEST_OPT_DEPENDENCY}" ]]; then
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
        if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        fi
        bash miniconda.sh -b -p $HOME/miniconda;
        export PATH="$HOME/miniconda/bin:$PATH";
        hash -r;
        conda config --set always_yes yes --set changeps1 no;
        conda update -q conda;
        conda config --prepend channels conda-forge --prepend channels symengine/label/dev;
        conda info -a;
        conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip ${TEST_OPT_DEPENDENCY/autowrap/libgfortran libgcc gcc cython};
        source activate test-environment;
    elif [ "$TRAVIS_PYTHON_VERSION" != "pypy" ]; then
        pip list --format=legacy | grep "numpy" && pip uninstall -y numpy;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pip install matchpy;
    fi
install:
  # If a command fails, fail the build.
  - set -e
#The install cycle below is to test installation on systems without setuptools.
  - if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ];
      then virtualenv -p /usr/bin/pypy ~/.venv;
           . ~/.venv/bin/activate;
    fi
  # -We:invalid makes invalid escape sequences error in Python 3.6. See
  # -#12028.
  - if [[ "${TEST_SAGE}" != "true" ]]; then
      pip install mpmath;
      pip uninstall -y setuptools;
      python -We:invalid setup.py install;
      pip uninstall -y sympy;
      pip install --upgrade setuptools;
      python -We:invalid -m compileall -f sympy/ || (echo "ERROR Invalid escape sequence found. You likely need to use a raw string." && exit 1);
      python -We:invalid setup.py install;
      pip list --format=columns;
    fi
script:
  # Don't run doctr if the build fails
  - set -e
  - bin/test_travis.sh
notifications:
  email: false
